name: GenerateEnsemble 

on:

  workflow_dispatch:

  workflow_run:
    workflows: [GenerateBaseline]
      
    types:
      - completed
    
jobs:

  verify_ensemble_job:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository_owner == 'Testing-Forecast-Actions' }}
    runs-on: ubuntu-latest

    steps:
      
    # Checkout the python tools repo
    # -------------------------------------------      
    - name: Test only
      run: |
        echo "Ensemble Running"
